import test from 'node:test';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import fs from 'node:fs';
const source=fs.readFileSync(new URL('../assets/gearly/gearly.js',import.meta.url),'utf8');
const raw={meta:{siteBase:'/asme',contactEmail:'asme@example.org'},pages:[{id:'join',title:'Join',url:'/asme/join/'}],intents:[{id:'join',examples:['join'],keywords:{join:3},response:{text:'<img src=x onerror=alert(1)>',cards:[{title:'Bad',url:'javascript:alert(1)'},{title:'Join',url:'/asme/join/'}],chips:['Join']}}]};
async function start(data=raw){const dom=new JSDOM('<body><main>Site</main></body>',{url:'https://org.osu.edu/asme/',runScripts:'outside-only'});dom.window.AbortSignal=AbortSignal;dom.window.fetch=async url=>({ok:true,json:async()=>url.includes('sprites.json')?{}:data});dom.window.matchMedia=()=>({matches:true});dom.window.eval(source);await new Promise(r=>setTimeout(r,20));return dom;}
test('dialog focus, Escape, safe response text and links',async()=>{const dom=await start();const w=dom.window;assert.ok(w.Gearly);w.Gearly.open();assert.equal(w.document.activeElement.className,'gearly-input');await w.Gearly.ask('join');assert.equal(w.document.querySelectorAll('.gearly-message img').length,0);assert.ok(w.document.querySelector('.gearly-message').textContent);assert.equal(w.document.querySelectorAll('a[href^="javascript:"]').length,0);w.document.querySelector('.gearly-panel').dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert.equal(w.document.querySelector('.gearly-panel').hidden,true);assert.equal(w.document.activeElement.className,'gearly-launcher');assert.equal(w.document.querySelector('.gearly-messages').getAttribute('aria-live'),'polite');dom.window.close();});
test('malformed data never renders launcher',async()=>{const dom=await start({});assert.equal(dom.window.document.querySelector('.gearly-launcher'),null);dom.window.close();});
test('session history stays capped at fifty messages',async()=>{const dom=await start();for(let i=0;i<30;i++)await dom.window.Gearly.ask('join');assert.ok(JSON.parse(dom.window.sessionStorage.getItem('gearly_state_v1')).history.length<=50);dom.window.close();});
test('live event requests receive slots and configure local repository base',async()=>{const dom=new JSDOM('<body></body>',{url:'https://org.osu.edu/asme/',runScripts:'outside-only'});const w=dom.window;w.AbortSignal=AbortSignal;w.matchMedia=()=>({matches:true});let slots,config;w.GearlyLive={configure:x=>config=x,load:async(k,s)=>{slots=s;return {text:'Filtered events',cards:[]};}};const seed={...raw,intents:[{id:'events',examples:['events next week'],keywords:{events:3},liveSource:'events',response:{text:'Events'}}]};w.fetch=async()=>({ok:true,json:async()=>seed});w.eval(source);await new Promise(r=>setTimeout(r,20));await w.Gearly.ask('events next week');assert.equal(slots.dateRange.label,'next-week');assert.ok(config.baseURL);dom.window.close();});
test('optimized sprites update launcher and avatar, safe restored history is rendered',async()=>{const dom=new JSDOM('<body></body>',{url:'https://org.osu.edu/asme/',runScripts:'outside-only'});const w=dom.window;w.AbortSignal=AbortSignal;w.matchMedia=()=>({matches:true});w.sessionStorage.setItem('gearly_state_v1',JSON.stringify({history:[{who:'user',text:'Previous question'}]}));const seed={...raw,meta:{...raw.meta,sprites:{idle:'sprites/idle.webp',happy:'sprites/happy.webp',thinking:'sprites/thinking.webp'}}};w.fetch=async()=>({ok:true,json:async()=>seed});w.eval(source);await new Promise(r=>setTimeout(r,20));assert.ok(w.document.querySelector('.gearly-messages').textContent.includes('Previous question'));assert.ok(w.document.querySelector('.gearly-launcher img').src.endsWith('idle.webp'));await w.Gearly.ask('join');assert.ok(w.document.querySelector('.gearly-avatar img').src.endsWith('happy.webp'));assert.ok(w.document.querySelector('.gearly-launcher img').src.endsWith('happy.webp'));dom.window.close();});
