import test from 'node:test';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import fs from 'node:fs';
const source=fs.readFileSync(new URL('../assets/gearly/gearly.js',import.meta.url),'utf8');
const raw={meta:{siteBase:'/asme',contactEmail:'asme@example.org'},pages:[{id:'join',title:'Join',url:'/asme/join/'}],intents:[{id:'join',examples:['join'],keywords:{join:3},response:{text:'<img src=x onerror=alert(1)>',cards:[{title:'Bad',url:'javascript:alert(1)'},{title:'Join',url:'/asme/join/'}],chips:['Join']}}]};
async function start(data=raw,setup){const dom=new JSDOM('<body><main>Site</main></body>',{url:'https://org.osu.edu/asme/',runScripts:'outside-only'});dom.window.AbortSignal=AbortSignal;dom.window.fetch=async url=>({ok:true,json:async()=>url.includes('sprites.json')?{}:data});dom.window.matchMedia=()=>({matches:true});if(setup)setup(dom.window);dom.window.eval(source);await new Promise(r=>setTimeout(r,20));return dom;}
test('dialog focus, Escape, safe response text and links',async()=>{const dom=await start();const w=dom.window;assert.ok(w.Gearly);w.Gearly.open();assert.equal(w.document.activeElement.className,'gearly-input');await w.Gearly.ask('join');assert.equal(w.document.querySelectorAll('.gearly-message img').length,0);assert.ok(w.document.querySelector('.gearly-message').textContent);assert.equal(w.document.querySelectorAll('a[href^="javascript:"]').length,0);w.document.querySelector('.gearly-panel').dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert.equal(w.document.querySelector('.gearly-panel').hidden,true);assert.equal(w.document.activeElement.className,'gearly-launcher');assert.equal(w.document.querySelector('.gearly-messages').getAttribute('aria-live'),'polite');dom.window.close();});
test('malformed data never renders launcher',async()=>{const dom=await start({});assert.equal(dom.window.document.querySelector('.gearly-launcher'),null);dom.window.close();});
test('closed guide exposes only a compact sprite launcher with tour inside the panel',async()=>{const dom=await start({...raw,meta:{...raw.meta,sprites:{idle:'sprites/idle.webp'}}});const w=dom.window;const launcher=w.document.querySelector('.gearly-launcher');assert.equal(launcher.textContent,'');assert.ok(launcher.querySelector('img'));assert.equal(w.document.querySelector('.gearly-root > .gearly-tour-replay'),null);assert.ok(w.document.querySelector('.gearly-header .gearly-tour-replay'));assert.equal(launcher.getAttribute('aria-label'),'Open Gearly, ASME website guide');dom.window.close();});
test('session history stays capped at fifty messages',async()=>{const dom=await start();for(let i=0;i<30;i++)await dom.window.Gearly.ask('join');assert.ok(JSON.parse(dom.window.sessionStorage.getItem('gearly_state_v1')).history.length<=50);dom.window.close();});
test('live event requests receive slots and configure local repository base',async()=>{const dom=new JSDOM('<body></body>',{url:'https://org.osu.edu/asme/',runScripts:'outside-only'});const w=dom.window;w.AbortSignal=AbortSignal;w.matchMedia=()=>({matches:true});let slots,config;w.GearlyLive={configure:x=>config=x,load:async(k,s)=>{slots=s;return {text:'Filtered events',cards:[]};}};const seed={...raw,intents:[{id:'events',examples:['events next week'],keywords:{events:3},liveSource:'events',response:{text:'Events'}}]};w.fetch=async()=>({ok:true,json:async()=>seed});w.eval(source);await new Promise(r=>setTimeout(r,20));await w.Gearly.ask('events next week');assert.equal(slots.dateRange.label,'next-week');assert.ok(config.baseURL);dom.window.close();});
test('optimized sprites update launcher and avatar, safe restored history is rendered',async()=>{const dom=new JSDOM('<body></body>',{url:'https://org.osu.edu/asme/',runScripts:'outside-only'});const w=dom.window;w.AbortSignal=AbortSignal;w.matchMedia=()=>({matches:true});w.sessionStorage.setItem('gearly_state_v1',JSON.stringify({history:[{who:'user',text:'Previous question'}]}));const seed={...raw,meta:{...raw.meta,sprites:{idle:'sprites/idle.webp',happy:'sprites/happy.webp',thinking:'sprites/thinking.webp'}}};w.fetch=async()=>({ok:true,json:async()=>seed});w.eval(source);await new Promise(r=>setTimeout(r,20));assert.ok(w.document.querySelector('.gearly-messages').textContent.includes('Previous question'));assert.ok(w.document.querySelector('.gearly-launcher img').src.endsWith('idle.webp'));await w.Gearly.ask('join');assert.ok(w.document.querySelector('.gearly-avatar img').src.endsWith('happy.webp'));assert.ok(w.document.querySelector('.gearly-launcher img').src.endsWith('idle.webp'));dom.window.close();});

test('feature flag disables the assistant without rendering controls',async()=>{const dom=await start({...raw,meta:{...raw.meta,enabled:false}});assert.equal(dom.window.Gearly,undefined);assert.equal(dom.window.document.querySelector('.gearly-root'),null);dom.window.close();});
test('page suggestions and clear chat reset conversation and stored context',async()=>{const seed={...raw,pages:[{id:'join',title:'Join',url:'/asme/',suggestions:['Newsletter','GroupMe']}]};const dom=await start(seed);const w=dom.window;assert.equal(w.document.querySelector('.gearly-chips').textContent,'NewsletterGroupMe');await w.Gearly.ask('join');w.document.querySelector('[aria-label="Clear chat"]').click();const state=JSON.parse(w.sessionStorage.getItem('gearly_state_v1'));assert.equal(state.lastIntent,null);assert.equal(state.history.length,1);assert.ok(w.document.querySelector('.gearly-welcome'));assert.equal(w.document.querySelectorAll('.gearly-message').length,1);assert.equal(w.document.querySelector('.gearly-chips').textContent,'NewsletterGroupMe');dom.window.close();});
test('tour is configured, offered after a quiet delay, and can be replayed',async()=>{const dom=new JSDOM('<body></body>',{url:'https://org.osu.edu/asme/',runScripts:'outside-only'});const w=dom.window;w.AbortSignal=AbortSignal;w.matchMedia=()=>({matches:true});let offered=0,replayed=0,dismissed=0,configured,delayed;w.GearlyTour={configure:x=>configured=x,offer:()=>offered++,start:()=>replayed++,dismissOffer:()=>dismissed++};w.setTimeout=(cb,ms)=>{if(ms===4000)delayed=cb;return 0;};w.fetch=async()=>({ok:true,json:async()=>({...raw,tour:{version:1,steps:[]}})});w.eval(source);await new Promise(r=>setTimeout(r,20));assert.ok(configured.data.tour);assert.equal(offered,0);delayed();assert.equal(offered,1);w.document.querySelector('.gearly-tour-replay').click();assert.equal(replayed,1);assert.equal(w.document.querySelector('.gearly-panel').hidden,true);w.Gearly.open();assert.equal(dismissed,1);dom.window.close();});
test('clearing during a live request prevents stale answers reappearing',async()=>{const dom=new JSDOM('<body></body>',{url:'https://org.osu.edu/asme/',runScripts:'outside-only'});const w=dom.window;w.AbortSignal=AbortSignal;w.matchMedia=()=>({matches:true});let resolve;w.GearlyLive={configure:()=>{},load:()=>new Promise(r=>resolve=r)};w.fetch=async()=>({ok:true,json:async()=>({...raw,intents:[{id:'events',examples:['events'],response:{text:'Events'},liveSource:'events'}]})});w.eval(source);await new Promise(r=>setTimeout(r,20));const pending=w.Gearly.ask('events');w.document.querySelector('[aria-label="Clear chat"]').click();resolve({text:'Outdated pending answer',cards:[]});await pending;assert.ok(!w.document.querySelector('.gearly-messages').textContent.includes('Outdated'));assert.equal(JSON.parse(w.sessionStorage.getItem('gearly_state_v1')).lastIntent,null);dom.window.close();});


test('fresh welcome shortcuts, context, tour, and topic browsing work without sending a query',async()=>{
 const dom=await start({...raw,pages:[{id:'home',title:'Home',url:'https://org.osu.edu/asme/'}]});const w=dom.window;
 assert.match(w.document.querySelector('.gearly-context').textContent,/Helping with: Home/);
 assert.equal(w.document.querySelector('.gearly-welcome-sprite').alt,'Gearly waving hello');
 assert.equal(w.document.querySelectorAll('.gearly-shortcut').length,4);
 let toured=0;w.GearlyTour={start:()=>toured++};Array.from(w.document.querySelectorAll('.gearly-shortcut')).find(b=>b.textContent==='Take a tour').click();assert.equal(toured,1);assert.equal(w.document.querySelector('.gearly-panel').hidden,true);
 w.Gearly.open();Array.from(w.document.querySelectorAll('.gearly-text-button')).find(b=>b.textContent.includes('Browse')).click();assert.equal(w.document.querySelector('.gearly-welcome'),null);assert.match(w.document.querySelector('.gearly-chips').textContent,/Member points/);assert.equal(w.document.querySelectorAll('.gearly-user').length,0);dom.window.close();
});
test('thinking changes to typing and a complete accessible answer; reduced motion skips the reveal',async()=>{
 const seed={...raw,meta:{...raw.meta,sprites:{idle:'idle.webp',thinking:'think.webp',typing:'type.webp',happy:'happy.webp'}}};const dom=await start(seed);const w=dom.window;w.matchMedia=()=>({matches:false});
 const pending=w.Gearly.ask('join');assert.ok(w.document.querySelector('.gearly-activity'));assert.equal(w.document.querySelector('.gearly-avatar').dataset.state,'thinking');assert.equal(w.document.querySelector('.gearly-messages').getAttribute('aria-busy'),'true');
 await new Promise(r=>setTimeout(r,340));assert.equal(w.document.querySelector('.gearly-avatar').dataset.state,'typing');assert.ok(w.document.querySelector('.gearly-typing-label'));assert.equal(w.document.querySelector('.gearly-message:last-child a').hidden,true);
 await pending;assert.equal(w.document.querySelector('.gearly-typing-label'),null);assert.equal(w.document.querySelector('.gearly-activity'),null);assert.equal(w.document.querySelector('.gearly-message:last-child a').hidden,false);assert.equal(w.document.querySelector('.gearly-message:last-child p').hasAttribute('aria-hidden'),false);assert.equal(w.document.querySelector('.gearly-avatar').dataset.state,'happy');
 w.matchMedia=()=>({matches:true});const immediate=w.Gearly.ask('join');assert.equal(w.document.querySelector('.gearly-typing-label'),null);await immediate;dom.window.close();
});
test('clear during the animated reply cancels reveal and restores the welcome',async()=>{
 const dom=await start();const w=dom.window;w.matchMedia=()=>({matches:false});const pending=w.Gearly.ask('join');await new Promise(r=>setTimeout(r,340));w.document.querySelector('[aria-label="Clear chat"]').click();await pending;
 assert.ok(w.document.querySelector('.gearly-welcome'));assert.equal(w.document.querySelector('.gearly-typing-label'),null);assert.equal(w.document.querySelector('.gearly-activity'),null);assert.equal(w.document.querySelector('.gearly-messages').hasAttribute('aria-busy'),false);assert.ok(!w.document.querySelector('.gearly-messages').textContent.includes('<img'));assert.equal(w.document.querySelector('.gearly-avatar').dataset.state,'idle');dom.window.close();
});


test('explicit section requests open the section; information questions get interactive destination cards',async()=>{
 const action={type:'scrollTo',page:'https://org.osu.edu/asme/',selector:'#ranking',label:'Show ranking chart',title:'Public ranking chart'};const seed={...raw,intents:[{id:'leaderboard',examples:['pull up the ranking chart','who leads the leaderboard'],response:{text:'The public chart has current standings.'},actions:[action]}]};let opened;
 const dom=await start(seed,w=>{w.GearlyTour={configure:()=>{},showSection:a=>{opened=a;return true;},clearSection:()=>{}};});const w=dom.window;
 await w.Gearly.ask('pull up the ranking chart');assert.equal(opened.selector,'#ranking');assert.equal(w.document.querySelector('.gearly-panel').hidden,true);opened=null;
 await w.Gearly.ask('who leads the leaderboard');assert.equal(opened,null);const card=w.document.querySelector('.gearly-place-card');assert.ok(card.querySelector('img'));assert.equal(card.getAttribute('aria-label'),'Show ranking chart');card.click();assert.equal(opened.selector,'#ranking');dom.window.close();
});

test('mascot reactions work with keyboard and pointer, and pending sprites clear on reset',async()=>{
 const seed={...raw,meta:{...raw.meta,sprites:{idle:'sprites/gearly-neutral-head.webp',launcher:'sprites/gearly-happy-head.webp',thinking:'sprites/gearly-thinking-chin.webp'}}};
 let resolve;
 const dom=await start({...seed,intents:[{id:'events',examples:['events'],response:{text:'Current events'},liveSource:'events'}]},w=>{w.GearlyLive={configure:()=>{},load:()=>new Promise(r=>resolve=r)};});const w=dom.window;
 const join=Array.from(w.document.querySelectorAll('.gearly-shortcut')).find(el=>el.getAttribute('aria-label')==='Join ASME'),sprite=join.querySelector('img');
 assert.match(sprite.src,/double-thumbs-up/);join.focus();assert.match(sprite.src,/celebrating-jump/);
 w.Gearly.open();await new Promise(r=>setTimeout(r,10));assert.match(sprite.src,/double-thumbs-up/);
 join.dispatchEvent(new w.MouseEvent('mouseenter'));assert.match(sprite.src,/celebrating-jump/);join.dispatchEvent(new w.MouseEvent('mouseleave'));assert.match(sprite.src,/double-thumbs-up/);
 const pending=w.Gearly.ask('events');assert.match(w.document.querySelector('.gearly-activity-sprite').src,/thinking-chin/);
 w.document.querySelector('[aria-label="Clear chat"]').click();resolve({text:'Stale response'});await pending;
 assert.equal(w.document.querySelector('.gearly-activity-sprite'),null);assert.equal(w.document.querySelector('.gearly-reply-sprite'),null);dom.window.close();
});
