import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { JSDOM } from 'jsdom';
function page(file){const dom=new JSDOM(fs.readFileSync(file,'utf8'),{url:'https://org.osu.edu/asme/calendar/',runScripts:'outside-only'});const w=dom.window;w.matchMedia=()=>({matches:false,addEventListener(){},addListener(){}});w.AbortController=AbortController;return dom;}
async function calendar({failure=false,cached=false,events=[]}={}){
 const dom=page('Calendar Page.html'),w=dom.window;
 if(cached)w.localStorage.setItem('asmeCalendarEventsV4',JSON.stringify({savedAt:Date.now()-86400000,feed:{generatedAt:new Date(Date.now()-86400000).toISOString(),events}}));
 w.fetch=async()=>{if(failure)throw new Error('offline');return {ok:true,json:async()=>({generatedAt:new Date().toISOString(),events})};};
 w.eval(fs.readFileSync('Calendar Integration.js','utf8'));w.document.dispatchEvent(new w.Event('DOMContentLoaded'));await new Promise(resolve=>setTimeout(resolve,20));return dom;
}
const event={title:'Engineering workshop',start:new Date(Date.now()+86400000).toISOString(),end:new Date(Date.now()+90000000).toISOString(),location:'Existing room unchanged',description:'Bring your questions.'};
test('newsletter uses provider-owned form; no iframe load success handler',()=>{const dom=page('Join Page.html');assert.ok(dom.window.document.querySelector('iframe[title="ASME Ohio State newsletter signup form"]'));assert.equal(dom.window.document.querySelector('#asmeNewsletterForm'),null);assert.doesNotMatch(fs.readFileSync('Join Page Integration.js','utf8'),/addEventListener|form.reset|Step 1 complete/);dom.window.close();});
test('calendar network failure does not claim an empty schedule',async()=>{const dom=await calendar({failure:true});const text=dom.window.document.body.textContent;assert.match(text,/event list is unavailable/);assert.doesNotMatch(text,/No upcoming events are currently listed/);dom.window.close();});
test('calendar legitimate empty response has distinct message',async()=>{const dom=await calendar();assert.match(dom.window.document.body.textContent,/No upcoming events are currently listed/);assert.doesNotMatch(dom.window.document.body.textContent,/could not be loaded/);dom.window.close();});
test('calendar offline cache remains visible with warning and event actions',async()=>{const dom=await calendar({failure:true,cached:true,events:[event]});const d=dom.window.document;assert.match(d.body.textContent,/Showing saved events/);assert.match(d.querySelector('#asmeCalendarUpcoming').textContent,/Engineering workshop/);const url=new URL(d.querySelector('.asme-event-actions a').href);assert.equal(url.searchParams.get('location'),event.location);assert.equal(url.searchParams.get('action'),'TEMPLATE');dom.window.close();});
test('academic dates are opt-in and original event metadata is retained',async()=>{const academic={...event,title:'Labor Day - no classes, offices closed'};const dom=await calendar({events:[event,academic]});const w=dom.window,d=w.document;assert.equal(d.querySelectorAll('.acp-event-card').length,1);const check=d.getElementById('asmeIncludeAcademicDates');check.checked=true;check.dispatchEvent(new w.Event('change'));assert.equal(d.querySelectorAll('.acp-event-card').length,2);assert.match(d.body.textContent,/Existing room unchanged/);dom.window.close();});
test('sponsor draft is blocked when required fields are invalid',()=>{const dom=page('Sponsor ASME Page.html'),w=dom.window;w.eval(fs.readFileSync('Sponsor Integration.js','utf8'));w.document.dispatchEvent(new w.Event('DOMContentLoaded'));const link=w.document.querySelector('.sponsor-form-submit');const e=new w.MouseEvent('click',{bubbles:true,cancelable:true});assert.equal(link.dispatchEvent(e),false);assert.equal(link.textContent,'Open email draft →');assert.equal(w.document.querySelectorAll('input[required]').length,6);dom.window.close();});
test('sponsor dialog returns keyboard focus to selected tier',()=>{const dom=page('Sponsor ASME Page.html'),w=dom.window,d=w.document;w.eval(fs.readFileSync('Sponsor Integration.js','utf8'));d.dispatchEvent(new w.Event('DOMContentLoaded'));const button=d.querySelector('[data-sponsor-tier]');button.click();assert.equal(d.getElementById('sponsor-modal').hidden,false);d.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert.equal(d.getElementById('sponsor-modal').hidden,true);assert.equal(d.activeElement,button);dom.window.close();});
test('new home puts the next event before general membership content',()=>{const dom=page('Home Page.html');const d=dom.window.document;assert.ok(d.getElementById('asmeFeaturedEvent').compareDocumentPosition(d.querySelector('.ah-cards-grid'))&4);assert.equal(d.getElementById('ahDots'),null);dom.window.close();});
