import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd();
const pages={'/':'Home Page.html','/join/':'Join Page.html','/calendar/':'Calendar Page.html','/sponsor-asme/':'Sponsor ASME Page.html','/leadership/':'Leadership Page.html','/member-resources/':'Member Resources Page.html','/member-points-page/':'Member Points Page.html','/pictures/':'Gallery Page.html','/aboutus/':'About Us Page.html','/current-sponsors/':'Current Sponsors Page.html'};
const server=http.createServer((req,res)=>{
 const url=new URL(req.url,'http://localhost');let pathname=decodeURIComponent(url.pathname);
 if(pathname==='/backup') {
  const backupDir=path.resolve(root,'../ASME-website-backup-2026-09-05');
  if(req.method==='POST'){
   let body='';req.on('data',chunk=>{body+=chunk;if(body.length>2000000)req.destroy();});
   req.on('end',()=>{const form=new URLSearchParams(body),name=form.get('name');if(![...Object.values(pages),'Footer.html','Stylesheet.html'].includes(name)){res.writeHead(400);return res.end('Invalid backup name');}fs.mkdirSync(backupDir,{recursive:true});const file=path.join(backupDir,name);if(fs.existsSync(file)){res.writeHead(409);return res.end('Backup already exists; original preserved.');}fs.writeFileSync(file,form.get('content')||'');res.setHeader('Content-Type','text/html; charset=utf-8');res.end('<h1>Backup saved</h1><p>'+name+'</p><a href="/backup">Back to backup form</a>');});return;
  }
  res.setHeader('Content-Type','text/html; charset=utf-8');return res.end('<!doctype html><html lang="en"><title>Local ASME backup</title><h1>Save original WordPress HTML locally</h1><form method="post"><label>File name<input name="name" required></label><label>Original HTML<textarea name="content" required></textarea></label><button>Save backup</button></form></html>');
 }
 if(pathname.startsWith('/source/')){const name=pathname.slice(8);if(!Object.values(pages).includes(name)&&name!=='Footer.html'){res.writeHead(404);return res.end();}res.setHeader('Content-Type','text/plain; charset=utf-8');return res.end(fs.readFileSync(name));}
 if(pages[pathname]){
  const page=fs.readFileSync(pages[pathname],'utf8').replace(/https:\/\/asme-osu.github.io\/ASME-OSU-Website\//g,'/');
  const footer=fs.readFileSync('Footer.html','utf8').replace(/https:\/\/asme-osu.github.io\/ASME-OSU-Website\//g,'/');
  res.setHeader('Content-Type','text/html; charset=utf-8');
  return res.end(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ASME preview — ${pages[pathname]}</title><link rel="stylesheet" href="https://org.osu.edu/asme/wp-content/themes/generatepress/assets/css/main.min.css?ver=3.6.1"><link rel="stylesheet" href="/ASME%20Custom%20CSS.css"><style>body{margin:0}#page{max-width:1440px;margin:auto}.inside-header{display:flex;align-items:center;justify-content:space-between;max-width:1288px;margin:auto}.main-nav ul{display:flex;list-style:none;gap:5px;margin:0;padding:0}.main-nav a{padding:12px;display:block}.menu-toggle{display:none}@media(max-width:768px){.menu-toggle{display:block}.main-nav{display:none}.toggled .main-nav{display:block}.main-nav ul{display:flex;flex-wrap:wrap}}</style></head><body class="home page generatepress no-sidebar"><header id="masthead" class="site-header"><div class="inside-header"><div class="site-logo"><a href="/"><img src="https://org.osu.edu/asme/files/2026/04/ASME-Student-Section-Achievement-Award-2026.png" alt="ASME logo" width="46"></a></div><div class="site-branding"><p class="site-title"><a href="/">American Society of Mechanical Engineers</a></p></div><nav id="site-navigation" class="main-navigation"><button class="menu-toggle" aria-expanded="false" onclick="this.parentElement.classList.toggle('toggled');this.setAttribute('aria-expanded',this.parentElement.classList.contains('toggled'))"><span class="mobile-menu">Menu</span><span aria-hidden="true">☰</span></button><div class="main-nav"><ul><li><a href="/">Home</a></li><li><a href="/aboutus/">About</a></li><li><a href="https://org.osu.edu/asme/join/">Join</a></li><li><a href="/calendar/">Events</a></li><li><a href="/sponsor-asme/">Sponsors</a></li><li><a href="/pictures/">Gallery</a></li><li><a href="/leadership/">Leadership</a></li><li><a href="/member-resources/">Members</a></li></ul></div></nav></div></header><div id="page" class="site"><div id="content" class="site-content"><main class="site-main"><article><div class="entry-content">${page}</div></article></main></div></div><footer class="site-footer">${footer}</footer></body></html>`);
 }
 const file=path.resolve(root,'.'+pathname);if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);return res.end('Not found');}
 const type={'.css':'text/css','.js':'application/javascript','.json':'application/json','.html':'text/html','.png':'image/png','.jpg':'image/jpeg','.svg':'image/svg+xml'}[path.extname(file)]||'application/octet-stream';res.setHeader('Content-Type',type+'; charset=utf-8');res.end(fs.readFileSync(file));
});server.listen(4177,'127.0.0.1',()=>console.log('ASME preview: http://127.0.0.1:4177'));
